각자 오늘 할당량 채우려면 여기 repository 바꾸는것을 추천드립니다 
teammate : "최성우, 주보경, 이은서, 최선재"
print("starting line")
print("line two")
print("line three")
print("line four")
print("line five")
print("line six")
print("line seven")
print("line eight")
print("line nine")
print("line ten")
print("line eleven")
print("line twelve")
print("line twenty")
print("line one sentence")
